[package]
name = "ids"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
linfa = "0.7.0"
pcap = "1.2.0"
rocket = "0.5.0"
tch = "0.15.0"
